### ISSUE TITLE
Flaky test found validating Insider release 2.8.1

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#1108]
## Describe the bug

The E2E reliability build associated with Insider release 2.8.1 failed. The failure occurred only on the mac_3 job, and it succeeded on the runs before and after the 2.8.1 release.

Link to failing build: https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=32155&view=logs

Excerpt from log:

[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.155.1/work/_temp/6599ee67-bfba-4fd4-8102-6f1c271069d2.sh
yarn run v1.17.3
$ jest --projects src/tests/end-to-end --runInBand --ci
PASS e2e tests src/tests/end-to-end/tests/details-view/preview-features.test.ts (22.298s)
PASS e2e tests src/tests/end-to-end/tests/common/settings-drop-down.test.ts (21.956s)
PASS e2e tests src/tests/end-to-end/tests/popup/adhoc-panel.test.ts (70.601s)
PASS e2e tests src/tests/end-to-end/tests/popup/hamburger-menu.test.ts (17.188s)
PASS e2e tests src/tests/end-to-end/tests/details-view/headings.test.ts (31.694s)
PASS e2e tests src/tests/end-to-end/tests/popup/launchpad.test.ts (14.709s)
FAIL e2e tests src/tests/end-to-end/tests/content/a11y-content.test.ts (179.782s)
  ● Console

    console.log src/tests/end-to-end/common/generate-screenshot.ts:23
      Screenshot file is located at: /Users/vsts/agent/2.155.1/work/1/s/test-results/e2e/failure-screenshots/f79a36cb-7119-4772-8785-73e09c40cb20.png

  ● A11Y for content pages › High Contrast mode › test/headings/guidance

    TimeoutError: waiting for selector ".settings-panel" failed: timeout 5000ms exceeded

      112 |     public async waitForSelector(selector: string, options?: Puppeteer.WaitForSelectorOptions): Promise<Puppeteer.ElementHandle<Element>> {
      113 |         return await this.screenshotOnError(
    > 114 |             async () => await this.underlyingPage.waitForSelector(selector, { timeout: DEFAULT_PAGE_ELEMENT_WAIT_TIMEOUT_MS, ...options }),
          |                                                   ^
      115 |         );
      116 |     }
      117 | 

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:561:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:490:22)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/DOMWorld.js:444:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:628:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1089:29)
      at screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:114:51)
      at DetailsViewPage.screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:262:26)
      at DetailsViewPage.waitForSelector (src/tests/end-to-end/common/page-controllers/page.ts:113:27)
      at DetailsViewPage.openSettingsPanel (src/tests/end-to-end/common/page-controllers/details-view-page.ts:36:20)
## Screenshots

Screenshot from build--notice that it shows that the settings panel is open:

![image](https://user-images.githubusercontent.com/45672944/63389880-0505fa80-c362-11e9-9b65-4e171d44a93a.png)

**Comment by karanbirsingh** [comment]
same symptoms in CI build as well, ids 2115 & 2109
