### ISSUE TITLE
e2e flakiness: tabstop.test.ts failing for Mac 

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#1788]
## Describe the bug

The E2E reliability build failed for Insider 2.11.0, and there was one failure for e2e_tests_mac_2 job. 

Link to failing build: [https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=52609](url)

Excerpt from log:

```FAIL e2e tests src/tests/end-to-end/tests/target-page/tabstop.test.ts (20.364s)
  ● Console

    console.log src/tests/end-to-end/common/screenshot-on-error.ts:15
      Screenshot file is located at: /Users/runner/runners/2.160.1/work/1/s/test-results/e2e/failure-screenshots/7f951358-7d7a-4768-b363-9d40f7dffe9a.png

  ● Tab stops visualization › should show the expected visuals in the target page after enabling from popup and tabbing through target page

    TimeoutError: waiting for selector "button[aria-label="Tab stops"][aria-checked=true]" failed: timeout 15000ms exceeded

      129 |     public async waitForSelector(selector: string, options?: Puppeteer.WaitForSelectorOptions): Promise<Puppeteer.ElementHandle<Element>> {
      130 |         return await this.screenshotOnError(
    > 131 |             async () => await this.underlyingPage.waitForSelector(selector, { timeout: DEFAULT_PAGE_ELEMENT_WAIT_TIMEOUT_MS, ...options }),
          |                                                   ^
      132 |         );
      133 |     }
      134 | 

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:478:22)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/DOMWorld.js:432:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:627:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1125:29)
      at src/tests/end-to-end/common/page-controllers/page.ts:131:51
      at Object.screenshotOnError (src/tests/end-to-end/common/screenshot-on-error.ts:20:22)
      at PopupPage.screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:293:22)
      at PopupPage.waitForSelector (src/tests/end-to-end/common/page-controllers/page.ts:130:27)
      at PopupPage.enableToggleByAriaLabel (src/tests/end-to-end/common/page-controllers/popup-page.ts:23:20)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (src/tests/end-to-end/tests/target-page/tabstop.test.ts:28:9)`

**Comment by ferBonnin** [comment]
Reviewed with Peter, closing since this is stale
