### ISSUE TITLE
e2e flakiness: issue-dialog.test.ts

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#1789]
## Describe the bug

The E2E reliability build failed for Insider 2.11.0, and on one run there was a failure for the e2e_tests_linux_4 job; when re-queued, the same test failed for the e2e_tests_linux_1 job.

Link to failing builds: https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=52609 and https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=52406

Excerpt from log

```
FAIL e2e tests src/tests/end-to-end/tests/target-page/issue-dialog.test.ts (6.351s)
  ● Console

    console.log src/tests/end-to-end/common/screenshot-on-error.ts:15
      Screenshot file is located at: /app/test-results/e2e/failure-screenshots/e326a471-582d-456c-99b9-b4fa10bb5605.png

  ● Target Page issue dialog › should pass accessibility validation

    Node is either not visible or not an HTMLElement

      224 |     public async clickElementHandle(element: Puppeteer.ElementHandle<Element>): Promise<void> {
      225 |         await this.screenshotOnError(async () => {
    > 226 |             await element.click({ delay: DEFAULT_CLICK_MOUSEUP_DELAY_MS });
          |             ^
      227 |         });
      228 |     }
      229 | 

      at ElementHandle._clickablePoint (node_modules/puppeteer/lib/JSHandle.js:217:13)
          at runMicrotasks (<anonymous>)
      at ElementHandle.click (node_modules/puppeteer/lib/JSHandle.js:283:20)
      at src/tests/end-to-end/common/page-controllers/page.ts:226:13
      at Object.screenshotOnError (src/tests/end-to-end/common/screenshot-on-error.ts:20:16)
      at TargetPage.screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:293:16)
      at TargetPage.clickElementHandle (src/tests/end-to-end/common/page-controllers/page.ts:225:9)
      at TargetPage.clickDescendentSelector (src/tests/end-to-end/common/page-controllers/page.ts:221:9)
      at TargetPage.clickSelectorInShadowRoot (src/tests/end-to-end/common/page-controllers/target-page.ts:44:9)
      at Object.<anonymous> (src/tests/end-to-end/tests/target-page/issue-dialog.test.ts:34:9)
        -- ASYNC --
      at ElementHandle.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at src/tests/end-to-end/common/page-controllers/page.ts:226:27
      at Object.screenshotOnError (src/tests/end-to-end/common/screenshot-on-error.ts:20:22)
      at TargetPage.screenshotOnError (src/tests/end-to-end/common/page-controllers/page.ts:293:22)
      at TargetPage.clickElementHandle (src/tests/end-to-end/common/page-controllers/page.ts:225:20)
      at TargetPage.clickDescendentSelector (src/tests/end-to-end/common/page-controllers/page.ts:221:20)
          at runMicrotasks (<anonymous>)
      at TargetPage.clickSelectorInShadowRoot (src/tests/end-to-end/common/page-controllers/target-page.ts:44:9)
      at Object.<anonymous> (src/tests/end-to-end/tests/target-page/issue-dialog.test.ts:34:9)

**Comment by ferBonnin** [comment]
Reviewed with Peter, closing since this is stale
