### ISSUE TITLE
[Bug] Sporadically failing E2E tests

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#2201]
## Describe the bug

The Canary release was blocked recently by the same test failing in 3 consecutive runs. It eventually succeeded, but there was no indication of the cause of the failure or why it impacted this specific test. Opening this issue for tracking, although it may be something outside of our immediate control.

Detail from pipeline output:

```
yarn run v1.17.3
$ cross-env --max-old-space-size=16384 jest --projects src/tests/electron --runInBand --ci
FAIL electron tests src/tests/electron/tests/automated-checks-view.test.ts (86.41s)
  ● AutomatedChecksView › should not contain any accessibility issues

    thrown: "Exceeded timeout of 20000ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      17 |     let automatedChecksView: AutomatedChecksViewController;
      18 | 
    > 19 |     beforeEach(async () => {
         |     ^
      20 |         app = await createApplication();
      21 |         automatedChecksView = await app.openAutomatedChecksView();
      22 |         await automatedChecksView.waitForScreenshotViewVisible();

      at src/tests/electron/tests/automated-checks-view.test.ts:19:5
      at Object.<anonymous> (src/tests/electron/tests/automated-checks-view.test.ts:15:1)
```

The same test (`yarn test:unified`) passed locally

**Comment by ferBonnin** [comment]
Reviewed with Peter, closing since this is referenced in a PR to improve issue
