### ISSUE TITLE
build-unsigned-release-packages build flaky due to e2e test hook timeouts

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#2391]
## Describe the bug

On Windows, the build-unsigned-release-packages shows transient failures due to e2e test timeouts. An example log is listed below. It is possible that the hook timeout is not long enough for the application to start on the Windows build machines; the mac and linux tests do not seem to exhibit this issue.

```
Starting: run unified e2e tests (non-linux)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
yarn test:unified --ci
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\fb25ac7f-8295-412c-86bb-323cba0d91c8.cmd""
yarn run v1.17.3
$ cross-env --max-old-space-size=16384 jest --projects src/tests/electron --runInBand --ci
PASS electron tests src/tests/electron/tests/automated-checks-view.test.ts (69.519s)
FAIL electron tests src/tests/electron/tests/unified-settings-panel.test.ts (57.131s)
  ● AutomatedChecksView -> Settings Panel › High Contrast Mode toggle › should pass accessibility validation with highContrastMode=false

    thrown: "Exceeded timeout of 20000ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      12 |     let automatedChecksView: AutomatedChecksViewController;
      13 | 
    > 14 |     beforeEach(async () => {
         |     ^
      15 |         app = await createApplication({ suppressFirstTimeDialog: true });
      16 |         automatedChecksView = await app.openAutomatedChecksView();
      17 |         await automatedChecksView.waitForViewVisible();

      at src/tests/electron/tests/unified-settings-panel.test.ts:14:5
      at Object.<anonymous> (src/tests/electron/tests/unified-settings-panel.test.ts:10:1)

PASS electron tests src/tests/electron/tests/device-connection-dialog.test.ts (40.12s)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 1 skipped, 18 passed, 20 total
Snapshots:   0 total
Time:        167.786s
Ran all test suites.
Jest did not exit one second after the test run has completed.
```

**Comment by ferBonnin** [comment]
reviewed with @peterdur this is stale (opened a year ago) and there is a feature looking into E2E tests
