### ISSUE TITLE
Flaky web E2E: Details View -> Assessment -> Headings should pass accessibility validation

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2417]
## Describe the bug

In the past 30 days, [test analytics](https://dev.azure.com/ms/accessibility-insights-web/_test/analytics?definitionId=180&contextType=build) shows that these two test cases (the high contrast true and false versions) are by far the flakiest of the tests in the web E2E suite; they have 23 failures each, compared to 8 failures for the next-flakiest and <5 for every other test. Does not seem to be specific to any one OS.

Examples of e2e-reliability builds with corresponding failures:
* [#20200330.7](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=70839&view=ms.vss-test-web.build-test-results-tab)
* [#20200326.6](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=70322&view=results)
* [#20200325.2](https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=69943&view=results)

The specific symptom/stack/error message is consistent:

```
* TimeoutError: waiting for selector "[data-automation-id="instance-table-text-content"]" failed: timeout 15000ms exceeded
    at new WaitTask (D:\a\1\s\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (D:\a\1\s\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (D:\a\1\s\node_modules\puppeteer\lib\DOMWorld.js:432:17)
    at Frame.waitForSelector (D:\a\1\s\node_modules\puppeteer\lib\FrameManager.js:627:47)
    at Frame.<anonymous> (D:\a\1\s\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.waitForSelector (D:\a\1\s\node_modules\puppeteer\lib\Page.js:1122:29)
    at D:\a\1\s\src\tests\end-to-end\common\page-controllers\page.ts:151:43
    at Object.screenshotOnError (D:\a\1\s\src\tests\end-to-end\common\screenshot-on-error.ts:22:22)
    at DetailsViewPage.screenshotOnError (D:\a\1\s\src\tests\end-to-end\common\page-controllers\page.ts:320:22)
    at DetailsViewPage.waitForSelector (D:\a\1\s\src\tests\end-to-end\common\page-controllers\page.ts:149:27)
    at openHeadingsPage (D:\a\1\s\src\tests\end-to-end\tests\details-view\headings.test.ts:58:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at D:\a\1\s\src\tests\end-to-end\tests\details-view\headings.test.ts:23:24
    at _runTestsForDescribeBlock (D:\a\1\s\node_modules\jest-circus\build\run.js:43:5)
    at _runTestsForDescribeBlock (D:\a\1\s\node_modules\jest-circus\build\run.js:80:5)
    at run (D:\a\1\s\node_modules\jest-circus\build\run.js:23:3)
    at runAndTransformResultsToJestFormat (D:\a\1\s\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:177:21)
    at jestAdapter (D:\a\1\s\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:123:19)
    at runTestInternal (D:\a\1\s\node_modules\jest-runner\build\runTest.js:413:16)
    at runTest (D:\a\1\s\node_modules\jest-runner\build\runTest.js:487:34)
```

Screenshot of a test case during the failure state:
![Screenshot of a test case during the failure state](https://user-images.githubusercontent.com/376284/77958055-5592ee00-7289-11ea-8004-a52d56aa665c.png)

**Comment by ferBonnin** [comment]
per conversation with @peterdur closing as stale
