### ISSUE TITLE
Project doesn't build on M1 macbooks

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-web#4097]
## Describe the bug

Looks like the project doesn't get built on M1 mac because of `electron's` dependency.

M1 macs are supported on electron from version 11 according to this [blog post](https://www.electronjs.org/blog/electron-11-0#highlight-features).

**To Reproduce**

1. Build the project on any m1 device.

## Expected behavior

Should be able to `install`, `build` or `test` on a M1 system.

## Error Log

```
> npm install

> electron@9.4.4 postinstall /Users/****/****/a11yInsights/node_modules/react-devtools/node_modules/electron
> node install.js

HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/****/****/a11yInsights/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:315:20)
    at module.exports (/Users/****/****/a11yInsights/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/****/****/a11yInsights/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/****/****/a11yInsights/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
npm WARN @typescript-eslint/eslint-plugin@4.21.0 requires a peer of @typescript-eslint/parser@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.4.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@9.4.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

## Are you willing to submit a PR?

Sure. But looks like it might have to do something with the official microsoft electron released build that the project can use.

## Did you search for similar existing issues?

Yes.

**Comment by ferBonnin** [comment]
Per conversation with Peter, this will get addressed with feature work. @ferBonnin to add to the right feature.

**Comment by ferBonnin** [comment]
@madalynrose should this be marked as resolved?

**Comment by ferBonnin** [comment]
@Shobhit1 we have updated to Electron 11, can you please let us know if this works again?
Thanks!

**Comment by Shobhit1** [comment]
Hey @ferBonnin , 
Sorry for replying late. It works now. Thanks for the fix. :)
