### ISSUE TITLE
Building the unified client on MacOS errors out (potentially only on MacOS Monterey)

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#5331]
## Describe the bug

Specifically the part where we run `pack:unified:canary` causes the error to occur.

**To Reproduce**

1. Checkout main branch and run yarn.
2. Run `yarn build:unified:canary`.

## Expected behavior

Should build unified client successfully.

## Context (please complete the following information)

- OS Name & Version: MacOS 12.3 and 12.3.1 both repro.
- AI-Web Version & Environment: Unified
- electron-builder version 22.14.13

## Additional context

Normal error:

```
Fatal error: electron-builder exited with error code 1:

  • electron-builder  version=22.14.13 os=21.4.0
[...]
  • building        target=macOS zip arch=x64 file=drop/electron/unified-canary/packed/Accessibility Insights for Android - Canary.zip
  • building        target=DMG arch=x64 file=drop/electron/unified-canary/packed/Accessibility Insights for Android - Canary.dmg
  • Above command failed, retrying 5 more times
  • Above command failed, retrying 4 more times
  • Above command failed, retrying 3 more times
  • Above command failed, retrying 2 more times
  • Above command failed, retrying 1 more times
  • building block map  blockMapFile=drop/electron/unified-canary/packed/Accessibility Insights for Android - Canary.zip.blockmap
  • Above command failed, retrying 0 more times
  ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/****/Documents/githubrepos/web/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
error Command failed with exit code 1.
```
Here's the important bits of the error that we see when we run `export DEBUG_DMG=true` beforehand:

```
 detachTempimageFile: synchronous unmount /dev/disk8s1 returned 49168
retrying unmount (#1)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Accessibility Insights for Android - Canary 0.0.0 (/dev/disk8s1) returned 49168
retrying unmount (#2)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Accessibility Insights for Android - Canary 0.0.0 (/dev/disk8s1) returned 49168
retrying unmount (#3)...
detachTempImageFile: synchronous retry (#1) unmount /Volumes/Accessibility Insights for Android - Canary 0.0.0 (/dev/disk8s1) returned 49168
2022-04-05 19:27:03.116 diskimages-helper[9916:3279334] -processKernelRequest: flush received
2022-04-05 19:27:03.531 diskimages-helper[9916:3279334] -processKernelRequest: flush received
2022-04-05 19:27:03.555 diskimages-helper[9916:3279307] useEffectiveIDs*** euid/egid changed to 501,20 (uid/gid is 501,20)
DIHLDiskImageCreate() returned 49168
hdiutil: create: returning 49168
hdiutil: create failed - Resource busy
```

Seems to be a similar issue to:
https://github.com/electron-userland/electron-builder/issues/5431
https://github.com/electron-userland/electron-builder/issues/4606

**Comment by waabid** [comment]
@jalkire was able to validate that the build is green on MacOS 11.6.4.

**Comment by DaveTryon** [comment]
We won't be fixing this.
