### ISSUE TITLE
Flaky E2E test

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#867]
## Describe the bug

We have a flaky E2E test that shows up about once a week

**To Reproduce**

1. Create a PR
2. Look at the test output

Sample output (from buildId 22334):
```
##[section]Starting: run e2e tests
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
yarn test:e2e -- --ci
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.153.2/work/_temp/59db13e1-f3e1-4a58-ad0f-a81a9b872d47.sh
yarn run v1.16.0
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ jest --projects src/tests/end-to-end --runInBand --ci
FAIL e2e tests src/tests/end-to-end/tests/common/settings-drop-down.test.ts (52.989s)
  ● Console

    console.log src/tests/end-to-end/common/generate-screenshot.ts:17
      Screenshot file is located at: /Users/vsts/agent/2.153.2/work/1/s/test-results/e2e/failure-screenshots/245b4dc3-bccd-4df7-967c-baf53c4e9e10.png

  ● Settings Dropdown › High contrast mode › should pass accessibility validation in popup dropdown

    TimeoutError: Navigation Timeout Exceeded: 5000ms exceeded

      27 | 
      28 |     public async goto(url: string): Promise<void> {
    > 29 |         await this.screenshotOnError(async () => await this.underlyingPage.goto(url, { timeout: DEFAULT_NEW_PAGE_WAIT_TIMEOUT_MS }));
         |                                                                            ^
      30 |     }
      31 | 
      32 |     public async close(ignoreIfAlreadyClosed: boolean = false): Promise<void> {

      at Promise.then (node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (node_modules/puppeteer/lib/Page.js:629:49)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.<anonymous> (src/tests/end-to-end/common/page.ts:29:76)
      at step (src/tests/end-to-end/common/page.ts:31:23)
      at Object.next (src/tests/end-to-end/common/page.ts:12:53)
      at src/tests/end-to-end/common/page.ts:6:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page.ts:2:12)
      at src/tests/end-to-end/common/page.ts:29:38
      at Page.<anonymous> (src/tests/end-to-end/common/page.ts:117:26)
      at step (src/tests/end-to-end/common/page.ts:31:23)
      at Object.next (src/tests/end-to-end/common/page.ts:12:53)
      at src/tests/end-to-end/common/page.ts:6:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page.ts:2:12)
      at Page.Object.<anonymous>.Page.screenshotOnError (src/tests/end-to-end/common/page.ts:294:16)
      at Page.<anonymous> (src/tests/end-to-end/common/page.ts:29:20)
      at step (src/tests/end-to-end/common/page.ts:31:23)
      at Object.next (src/tests/end-to-end/common/page.ts:12:53)
      at src/tests/end-to-end/common/page.ts:6:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page.ts:2:12)
      at Page.Object.<anonymous>.Page.goto (src/tests/end-to-end/common/page.ts:59:16)
      at Browser.<anonymous> (src/tests/end-to-end/common/browser.ts:30:20)
      at step (src/tests/end-to-end/common/browser.ts:31:23)
      at Object.next (src/tests/end-to-end/common/browser.ts:12:53)
      at fulfilled (src/tests/end-to-end/common/browser.ts:3:58)

FAIL e2e tests src/tests/end-to-end/tests/details-view/preview-features.test.ts (39.053s)
  ● Preview Features Panel › High contrast mode › should pass accessibility validation

    thrown: "Exceeded timeout of 20000ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      44 |         let detailsViewPage: Page;
      45 | 
    > 46 |         beforeAll(async () => {
         |         ^
      47 |             browser = await launchBrowser({ suppressFirstTimeDialog: true });
      48 | 
      49 |             targetTabId = (await browser.setupNewTargetPage()).tabId;

      at src/tests/end-to-end/tests/details-view/preview-features.test.ts:46:9
      at src/tests/end-to-end/tests/details-view/preview-features.test.ts:41:5
      at Object.<anonymous> (src/tests/end-to-end/tests/details-view/preview-features.test.ts:12:1)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Screenshot file is located at: /Users/vsts/agent/2.153.2/work/1/s/test-results/e2e/failure-screenshots/7a8ace2a-8626-4a7e-b260-4dc81519974e.png".

      15 |     const screenshotName = generateUID();
      16 |     const filePath = path.join(screenshotsPath, toFilename(`${screenshotName}.png`));
    > 17 |     console.log(`Screenshot file is located at: ${filePath}`);
         |             ^
      18 |     return await pageInstance.screenshot({
      19 |         path: filePath,
      20 |         fullPage: true,

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at Object.<anonymous> (src/tests/end-to-end/common/generate-screenshot.ts:17:13)
      at step (src/tests/end-to-end/common/generate-screenshot.ts:31:23)
      at Object.next (src/tests/end-to-end/common/generate-screenshot.ts:12:53)
      at fulfilled (src/tests/end-to-end/common/generate-screenshot.ts:3:58)

PASS e2e tests src/tests/end-to-end/tests/popup/adhoc-panel.test.ts (72.223s)
FAIL e2e tests src/tests/end-to-end/tests/popup/hamburger-menu.test.ts (34.74s)
  ● Hamburger menu › high contrast mode › should pass accessibility validation

    thrown: "Exceeded timeout of 20000ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      46 |         let popupPage: Page;
      47 | 
    > 48 |         beforeAll(async () => {
         |         ^
      49 |             browser = await launchBrowser({ suppressFirstTimeDialog: true });
      50 |             targetPageInfo = await browser.setupNewTargetPage();
      51 |             const detailsViewPage = await browser.newExtensionDetailsViewPage(targetPageInfo.tabId);

      at src/tests/end-to-end/tests/popup/hamburger-menu.test.ts:48:9
      at src/tests/end-to-end/tests/popup/hamburger-menu.test.ts:43:5
      at Object.<anonymous> (src/tests/end-to-end/tests/popup/hamburger-menu.test.ts:11:1)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Screenshot file is located at: /Users/vsts/agent/2.153.2/work/1/s/test-results/e2e/failure-screenshots/9845ce71-144e-405b-a98e-85784dc89dae.png".

      15 |     const screenshotName = generateUID();
      16 |     const filePath = path.join(screenshotsPath, toFilename(`${screenshotName}.png`));
    > 17 |     console.log(`Screenshot file is located at: ${filePath}`);
         |             ^
      18 |     return await pageInstance.screenshot({
      19 |         path: filePath,
      20 |         fullPage: true,

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at Object.<anonymous> (src/tests/end-to-end/common/generate-screenshot.ts:17:13)
      at step (src/tests/end-to-end/common/generate-screenshot.ts:31:23)
      at Object.next (src/tests/end-to-end/common/generate-screenshot.ts:12:53)
      at fulfilled (src/tests/end-to-end/common/generate-screenshot.ts:3:58)

FAIL e2e tests src/tests/end-to-end/tests/popup/launchpad.test.ts (34.755s)
  ● Launch Pad › High contrast mode › should pass accessibility validation

    thrown: "Exceeded timeout of 20000ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      44 |         let popupPage: Page;
      45 | 
    > 46 |         beforeAll(async () => {
         |         ^
      47 |             browser = await launchBrowser({ suppressFirstTimeDialog: true });
      48 |             targetPageInfo = await browser.setupNewTargetPage();
      49 |             const detailsViewPage = await browser.newExtensionDetailsViewPage(targetPageInfo.tabId);

      at src/tests/end-to-end/tests/popup/launchpad.test.ts:46:9
      at src/tests/end-to-end/tests/popup/launchpad.test.ts:41:5
      at Object.<anonymous> (src/tests/end-to-end/tests/popup/launchpad.test.ts:11:1)


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Screenshot file is located at: /Users/vsts/agent/2.153.2/work/1/s/test-results/e2e/failure-screenshots/a031c72a-7c30-4557-b6e6-88924c1563b4.png".

      15 |     const screenshotName = generateUID();
      16 |     const filePath = path.join(screenshotsPath, toFilename(`${screenshotName}.png`));
    > 17 |     console.log(`Screenshot file is located at: ${filePath}`);
         |             ^
      18 |     return await pageInstance.screenshot({
      19 |         path: filePath,
      20 |         fullPage: true,

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at Object.<anonymous> (src/tests/end-to-end/common/generate-screenshot.ts:17:13)
      at step (src/tests/end-to-end/common/generate-screenshot.ts:31:23)
      at Object.next (src/tests/end-to-end/common/generate-screenshot.ts:12:53)
      at fulfilled (src/tests/end-to-end/common/generate-screenshot.ts:3:58)

FAIL e2e tests src/tests/end-to-end/tests/content/a11y-content.test.ts (630.381s)
  ● Console

    console.log src/tests/end-to-end/common/generate-screenshot.ts:17
      Screenshot file is located at: /Users/vsts/agent/2.153.2/work/1/s/test-results/e2e/failure-screenshots/dfb693ca-ca6c-4a08-9973-861b190fc7b7.png

  ● A11Y for content pages › High Contrast mode › test/headings/guidance

    TimeoutError: Navigation Timeout Exceeded: 5000ms exceeded

      27 | 
      28 |     public async goto(url: string): Promise<void> {
    > 29 |         await this.screenshotOnError(async () => await this.underlyingPage.goto(url, { timeout: DEFAULT_NEW_PAGE_WAIT_TIMEOUT_MS }));
         |                                                                            ^
      30 |     }
      31 | 
      32 |     public async close(ignoreIfAlreadyClosed: boolean = false): Promise<void> {

      at Promise.then (node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (node_modules/puppeteer/lib/Page.js:629:49)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.<anonymous> (src/tests/end-to-end/common/page.ts:29:76)
      at step (src/tests/end-to-end/common/page.ts:31:23)
      at Object.next (src/tests/end-to-end/common/page.ts:12:53)
      at src/tests/end-to-end/common/page.ts:6:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page.ts:2:12)
      at src/tests/end-to-end/common/page.ts:29:38
      at Page.<anonymous> (src/tests/end-to-end/common/page.ts:117:26)
      at step (src/tests/end-to-end/common/page.ts:31:23)
      at Object.next (src/tests/end-to-end/common/page.ts:12:53)
      at src/tests/end-to-end/common/page.ts:6:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page.ts:2:12)
      at Page.Object.<anonymous>.Page.screenshotOnError (src/tests/end-to-end/common/page.ts:294:16)
      at Page.<anonymous> (src/tests/end-to-end/common/page.ts:29:20)
      at step (src/tests/end-to-end/common/page.ts:31:23)
      at Object.next (src/tests/end-to-end/common/page.ts:12:53)
      at src/tests/end-to-end/common/page.ts:6:71
      at Object.<anonymous>.__awaiter (src/tests/end-to-end/common/page.ts:2:12)
      at Page.Object.<anonymous>.Page.goto (src/tests/end-to-end/common/page.ts:59:16)
      at Browser.<anonymous> (src/tests/end-to-end/common/browser.ts:30:20)
      at step (src/tests/end-to-end/common/browser.ts:31:23)
      at Object.next (src/tests/end-to-end/common/browser.ts:12:53)
      at fulfilled (src/tests/end-to-end/common/browser.ts:3:58)

PASS e2e tests src/tests/end-to-end/tests/popup/first-time-dialog.test.ts (31.079s)

Test Suites: 5 failed, 2 passed, 7 total
Tests:       5 failed, 217 passed, 222 total
Snapshots:   207 passed, 207 total
Time:        897.206s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Bash exited with code '1'.
##[section]Finishing: run e2e tests
```

**Comment by DaveTryon** [comment]
@smoralesd has seen this from time to time on his machine

**Comment by dbjorge** [comment]
With #1012, we're considering the broad class of flakiness to be adequately resolved. We'll start filing individual bugs for more specific classes of flakiness after this point.
